### PR TITLE
Gem Stack Sprites

### PR DESCRIPTION
**Pull request by Delegus**
Adds the + icon to all 35 gem stack variants. Sprite files and a minor update to items.json to point to the right files.

### CODE REVIEW

**Review by Bakelt — APPROVED** [review]
LGTM

**Comment by Delegus** [comment]
Didn't mean to submit the SOJ string change here but hey learning GitHub desktop app. :D Lol

**Comment by Delegus** [comment]
And yeah I messed something up. It's doing belt stats and A1 hireling fix all in this same thing, sorry...

**Review by CollinHerber — APPROVED** [review]
Everything looks good to me

**Pull request merged**
