### PR TITLE
Increases the Rune stack size to 50

### PR DESCRIPTION
**Pull request by CollinHerber**

### CODE REVIEW

**Review by EmpirePhil — COMMENTED** [review]
great!

**Review by EmpirePhil — APPROVED** [review]

**Comment by Harald92** [comment]
I actually did that already to 100 for Runes and Gems

**Comment by CollinHerber** [comment]
> I actually did that already for my game but up to 100 for Runes and Gems. The tricky part is that you have to implement the destacking for the new quanitity too, without it as soon as you reach the stack size which has no destacking recipe the item is useless. [misc.txt](https://github.com/user-attachments/files/17273240/misc.txt) [cubemain.txt](https://github.com/user-attachments/files/17273244/cubemain.txt)
> 
> The cubemain.txt has the socket punch changes, the one I send you in discord.

Good call, completely forgot about those

**Comment by CollinHerber** [comment]
Closing in favor of #108

**Pull request closed without merging**
