### PR TITLE
#261-MonsterAuraID

### PR DESCRIPTION
**Pull request by Bakelt**
- Many aura IDs are hard coded. This is causing Duriel's holy freeze to not work and monsters seem incapable of rolling holy fire/shock/freeze as auras
- Updated magicprefix.txt's Charged affix from 366 (old Warp ID) to 371 (new Warp ID)
- Reviewed magicprefixes, uniqueitems, sets, setitems and only found a "Charged" reference in magicprefixes
- Seems a column was inserted at some point. Copied blizz settings for the auras and they now work properly

### CODE REVIEW

**Comment by Bakelt** [comment]
image

**Comment by Bakelt** [comment]
Holy Shock sighted
image

**Comment by Bakelt** [comment]
Holy Fire spotted and damage confirmed. Also confirmed Duriel's aura now damages and slows

**Review by CollinHerber — APPROVED** [review]
Nice find

**Pull request merged**
