### PR TITLE
Orb of Assemblage

### PR DESCRIPTION
**Pull request by Vingelis**
Resolves: #337 

New orb that allows for conversion to set items.

### CODE REVIEW

**Review by CollinHerber — CHANGES_REQUESTED** [review]
I think it's rather mundane to just have a recipe that converts them back and forth. I'd instead make a treasureclass entry that picks one of the two to spawn

**Comment by Vingelis** [comment]
Have removed the cube recipe to convert the two and instead added the new orb to the Jewelry TC as suggested.

**Comment by Delegus** [comment]
This is going to cause a string issue; With how things are currently coded you need an ooa for the name and an ooaDescription for what the item does based on current text files.

**Comment by Delegus** [comment]
This is going to cause a string issue; With how things are currently coded you need an ooa for the name and an ooaDescription for what the item does based on current text files.

**Review by CollinHerber — APPROVED** [review]
LGTM

**Pull request merged**
