### PR TITLE
4 Socket Elite Druid Helms

### PR DESCRIPTION
**Pull request by Maowiwowi**
Druid pelts were left out when elite helms got 4 sockets *big sad* :.(

### CODE REVIEW

**Review by victoria-riley-barnett — APPROVED** [review]
looks good to me

**Comment by victoria-riley-barnett** [comment]
do you want this in 2.0, or in the hotfix :patch ?

**Comment by Harald92** [comment]
If we are at it, the Diadem got only 3 sockets too.

**Review by Harald92 — APPROVED** [review]
Looks good now.

**Pull request merged**
