### PR TITLE
NM-Hell Rebalance

### PR DESCRIPTION
**Pull request by Bakelt**
Resolves: #347
Resolves: #348 
Resolves: #349

HP/Damage balancing
- https://docs.google.com/spreadsheets/d/1IfLcxgyjTLy5cbTinahOaxxMc1KJdHZJB1KheuMqqOc/edit?usp=sharing

Terror Zones
- NM cap raised to 80

Hell Level Increase
- Zones increased by 8 levels. Min level from 67 to 80, Max level from 85 to 98
- Hell resist penalty increased from -100 to -120

Character Stats
- Mana regen reduced. Time to Max increased from 60s to 90s
- Life/vit, Mana/energy increased by ~25%

Monster Specifics
- Many monsters are faster
- Stygian Dolls use a new death explode skill instead of %HP deathdmg
- Fallen Shaman shoot 5 fireballs on Hell
- Unravelers undead holy bolt pierces on Hell
- Scarabs have a chance to cause a Nova on death
- Mummy family has a low chance for a random curse on death
- Summoner now has his own versions of the sorc skills with increased damage
- Duriel now has sarcophagus in his room that spawn cursed mummies
- Mephisto's council has been moved to defend him
- Diablo now can cast fire nova, meteor, and slow missiles on attack
- Ancients now have new abilities on hit and on death (Talic lightning, Madawc cold, Korlic fire)
- Baal will now [TBD]

Other
- Some tweaks for Druid summons from play test
- Inner Sight now applies a small amount of -PDR
- Decreased -PDR/-IAS on Decripify
- Decreased base -PDR on Amp Damage and made it scale linearly
- Added "ItemEffect" for some skills so they could be used for CtC effects

### CODE REVIEW

**Comment by CollinHerber** [comment]
I think Hell Mobs should also be a bit faster, not just dmg + hp numbers. If we can pull that off

**Comment by Bakelt** [comment]
First pass at 4 of 5 acts done. Need to look at modifications for Andariel, Ancients, and Baal.

Note: Exp curve will probably need to be adjusted. Leveling was painfully slow due to the level gap and it felt necessary to grind NM TZ a bit just to avoid the exp penalty. Maybe we redo the curve a bit so it starts to hit at lvl80.

**Review by CollinHerber — APPROVED** [review]
Excited to see this

**Comment by Bakelt** [comment]
> Excited to see this

Definitely room for improvement but trying to toe the line between "looks cool" and "feels like D2". Biggest issue I've had with some of the initial changes is making stuff that doesn't become very problematic for melee (death-skill) or summoners (gethit-skill).

**Pull request merged**
