### PR TITLE
added item-names.json sorting/renumbering script

### PR DESCRIPTION
**Pull request by victoria-riley-barnett**
- script confirmed works, I ran it and dropped the sorted and renumbered item-names.json into my game. 
- Would you believe we actually only have ~4000 entries 😆 

Usage: node item-repair.js

### CODE REVIEW

**Comment by victoria-riley-barnett** [comment]
One note on running this: some other open PRs touch this file, they should all be accepted before we run it, I think

**Comment by Harald92** [comment]
Just out of curiosity, what does that script do? It sorts the item-names.json that much I understand but in what fassion?

**Comment by victoria-riley-barnett** [comment]
The IDs are completely arbitrary, and the way they're setup now its pretty likely someone will reuse an ID eventually and not realize it. This just makes it so that never happens, it sorts everything by ID, then renumbers them starting from 1060 (the first ID rn, probably arbitrary but I left that lol)

**Comment by victoria-riley-barnett** [comment]
I guess it could still happen, but it cleans up the odds of that happening and gives an easy fix: someone just has to run this on item-names.json, and then commit the new file.

**Comment by Harald92** [comment]
> I guess it could still happen, but it cleans up the odds of that happening and gives an easy fix: someone just has to run this on item-names.json, and then commit the new file.

Very nice and very usefull indeed. You can commit it too, or do you not want to hastle with that? I have zero background in script stuff and are a bit hesitant to run a script I do not 100% trust on my computer.

**Comment by victoria-riley-barnett** [comment]
> One note on running this: some other open PRs touch this file, they should all be accepted before we run it, I think

I was concerned abt running it now with PRs that touch item-names.json in the pipeline, I don't mind being the one to run it, but also anyone familiar with JS in the future will see this doesn't do anything bad lol

**Comment by victoria-riley-barnett** [comment]
You'd need node for it anyways

**Comment by victoria-riley-barnett** [comment]
hmm, going to close this for a bit until I figure out whats up - on a 2nd test with 1.21 fully setup, changing this file in this way caused CTD.

**Pull request closed without merging**
